### ISSUE TITLE
error : can't load 'smallLabelFont'

### ISSUE THREAD

**Issue by FollyMaddy** [wyatt8740/x48#1]
I experienced this error with your command in raspbian stretch:
pi@raspberrypi:~ $ x48 -initialize -reset -rom ~/.hp48/rom
x48: using XShm extension.
x48: /home/pi/.hp48/hp48 is a version 0.4.0 file, converting
x48: FATAL ERROR, exit.
  - can't load font '-*-fixed-bold-r-normal-*-14-*-*-*-*-*-iso8859-1'
  - Please change resource 'smallLabelFont'

The program worked with the following command :
( credits to > https://talk.maemo.org/archive/index.php/t-27888.html )
x48 -geometry +0+0 -xrm '*smallLabelFont: fixed' -xrm '*mediumLabelFont: fixed' -xrm '*largeLabelFont: fixed' -xrm '*connectionFont: fixed' -rom ~/.hp48/rom

**Comment by wyatt8740** [comment]
Is `xfonts-base` installed? (that's what it's called in normal debian, anyway.)

All that appears to be doing is changing the X resources to look for a different font.

`xfontsel` should tell you what fonts are available on your system (by letting you select a font).

I'd totally forgotten that I had this problem when I first built X48. It's just missing some traditional x11 bitmap fonts.

**Comment by FollyMaddy** [comment]
`xfonts-base` wasn't installed ( checked with command : `dpkg -s xfonts-base`).
I installed  `xfonts-base` .
Only after reboot `xfonsel` was seeing the added fonts.
This command was now working for me :
`pi@raspberrypi:~ $ x48 -rom ~/.hp48/rom`
This issue is solved. 
Thanks :-)

**Comment by wyatt8740** [comment]
I should add for any onlookers that in Debian, bitmap fonts tend to be disabled by default in modern releases.

I don't know if that matters for classic X programs like this specifically, but you could try `dpkg-reconfigure fontconfig-config` and enabling bitmap fonts at the prompt (and also `dpkg-reconfigure xfonts-base`) to rectify things if having xfonts-base alone wasn't enough for some reason. I have also had to reload X or reboot in the past for changes to take effect.

**Comment by FollyMaddy** [comment]
Thanks for adding new information 👍

**Comment by hsigrist** [comment]
Which is the equivalent of xfonts-base in artix linux?

**Comment by wyatt8740** [comment]
@hsigrist I have absolutely no idea what that is. Never heard of it before.

From a quick search, I am assuming it's Arch-derived with Systemd ripped out. If it's Arch-derived, I still have no idea. I run Debian Sid with systemd manually ripped out (not Devuan), and have never used Arch.

Whatever it is, it should install a bunch of `pcf` or `pcf.gz` fonts to somewhere like `/usr/share/fonts/X11/`.

I am *guessing* (again, [based on search results](https://archlinux.org/packages/?sort=&q=xorg-fonts&maintainer=&flagged=)) that you want `xorg-fonts-75dpi` and `xorg-fonts-100dpi`.

Maybe also `xorg-fonts-type1`, `xorg-fonts-misc`.

**Comment by dbarzin** [comment]
Use the command :

    x48 -connFont fixed

or define the alias :

    alias x48='x48 -connFont fixed'

**Comment by wyatt8740** [comment]
That'd also work.
